from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np
import pandas as pd


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    default_root = repo_root / "Dataset_new" / "72video" / "al_images"
    parser = argparse.ArgumentParser(
        description=(
            "Build a deployment decision curve for uncertainty-aware automatic RR "
            "reporting. The automatic/report decision uses only the precomputed "
            "non-truth algorithmic risk score; reference RR is used only for "
            "post-hoc evaluation of each operating point."
        )
    )
    parser.add_argument("--input-root", type=Path, default=default_root)
    parser.add_argument("--output-prefix", default="paper_repro")
    parser.add_argument("--corrected-prefix", default="paper_repro_quality_residual")
    parser.add_argument(
        "--quality-prefix",
        default="paper_repro_algorithmic_quality",
        help="Prefix for algorithmic quality predictions generated by build_rr_algorithmic_quality_context.py.",
    )
    parser.add_argument(
        "--min-exact-rate",
        type=float,
        default=0.90,
        help="Minimum exact-count rate for the recommended automatic-report operating point.",
    )
    parser.add_argument(
        "--max-mae",
        type=float,
        default=0.75,
        help="Maximum RR MAE for the recommended automatic-report operating point.",
    )
    return parser.parse_args()


def numeric(df: pd.DataFrame, column: str) -> pd.Series:
    if column not in df.columns:
        return pd.Series(np.nan, index=df.index, dtype=float)
    return pd.to_numeric(df[column], errors="coerce")


def regression_r2(y_true: pd.Series, y_pred: pd.Series) -> float:
    valid = pd.DataFrame({"truth": y_true, "pred": y_pred}).dropna()
    if len(valid) < 2:
        return math.nan
    truth = valid["truth"].to_numpy(dtype=float)
    pred = valid["pred"].to_numpy(dtype=float)
    ss_res = float(np.sum((truth - pred) ** 2))
    ss_tot = float(np.sum((truth - float(np.mean(truth))) ** 2))
    if ss_tot == 0.0:
        return math.nan
    return 1.0 - ss_res / ss_tot


def wilson_interval(successes: int, total: int, z: float = 1.959963984540054) -> tuple[float, float]:
    if total <= 0:
        return math.nan, math.nan
    phat = successes / total
    denom = 1.0 + z * z / total
    centre = phat + z * z / (2.0 * total)
    margin = z * math.sqrt((phat * (1.0 - phat) + z * z / (4.0 * total)) / total)
    low = (centre - margin) / denom
    high = (centre + margin) / denom
    return max(0.0, low), min(1.0, high)


def metric_values(subset: pd.DataFrame) -> dict[str, object]:
    truth_rr = numeric(subset, "truth_rr")
    pred_rr = numeric(subset, "signal_aware_safe_final_rr_bpm")
    truth_count = numeric(subset, "truth_count")
    pred_count = numeric(subset, "signal_aware_safe_final_peaks")
    rr_valid = pd.DataFrame({"truth": truth_rr, "pred": pred_rr}).dropna()
    count_valid = pd.DataFrame({"truth": truth_count, "pred": pred_count}).dropna()
    if rr_valid.empty:
        rr_mae = math.nan
        rr_rmse = math.nan
    else:
        rr_error = rr_valid["truth"].to_numpy(dtype=float) - rr_valid["pred"].to_numpy(dtype=float)
        rr_mae = float(np.mean(np.abs(rr_error)))
        rr_rmse = float(np.sqrt(np.mean(rr_error**2)))
    if count_valid.empty:
        exact_count = 0
        within_one_count = 0
        ge1 = 0
        ge2 = 0
        count_mae = math.nan
    else:
        count_error = count_valid["pred"].to_numpy(dtype=float) - count_valid["truth"].to_numpy(dtype=float)
        abs_error = np.abs(count_error)
        exact_count = int(np.sum(abs_error == 0))
        within_one_count = int(np.sum(abs_error <= 1))
        ge1 = int(np.sum(abs_error >= 1))
        ge2 = int(np.sum(abs_error >= 2))
        count_mae = float(np.mean(abs_error))
    exact_low, exact_high = wilson_interval(exact_count, len(count_valid))
    ge1_low, ge1_high = wilson_interval(ge1, len(count_valid))
    return {
        "rr_valid_videos": int(len(rr_valid)),
        "rr_r2": regression_r2(truth_rr, pred_rr),
        "rr_mae": rr_mae,
        "rr_rmse": rr_rmse,
        "count_valid_videos": int(len(count_valid)),
        "count_mae": count_mae,
        "exact_count": exact_count,
        "exact_rate": exact_count / len(count_valid) if len(count_valid) else math.nan,
        "exact_rate_wilson_low_95": exact_low,
        "exact_rate_wilson_high_95": exact_high,
        "within_one_count": within_one_count,
        "within_one_rate": within_one_count / len(count_valid) if len(count_valid) else math.nan,
        "abs_count_error_ge1": ge1,
        "abs_count_error_ge2": ge2,
        "auto_error_rate_ge1": ge1 / len(count_valid) if len(count_valid) else math.nan,
        "auto_error_rate_ge1_wilson_low_95": ge1_low,
        "auto_error_rate_ge1_wilson_high_95": ge1_high,
    }


def decision_row(data: pd.DataFrame, threshold: float) -> dict[str, object]:
    total = int(len(data))
    auto = data[numeric(data, "algorithmic_review_risk_score") <= threshold].copy()
    review = data.drop(auto.index).copy()
    row: dict[str, object] = {
        "risk_threshold": threshold,
        "operating_point": f"risk_le_{threshold:.2f}" if threshold < 1.0 else "always_auto",
        "auto_videos": int(len(auto)),
        "review_videos": int(len(review)),
        "auto_coverage": len(auto) / total if total else math.nan,
        "manual_review_load": len(review) / total if total else math.nan,
        "manual_review_reduction": len(auto) / total if total else math.nan,
        "uses_truth_for_decision": False,
    }
    row.update(metric_values(auto))

    full_abs = numeric(data, "signal_aware_safe_abs_count_error")
    review_abs = numeric(review, "signal_aware_safe_abs_count_error")
    total_ge1 = int((full_abs >= 1).sum())
    review_ge1 = int((review_abs >= 1).sum())
    total_ge2 = int((full_abs >= 2).sum())
    review_ge2 = int((review_abs >= 2).sum())
    row.update(
        {
            "total_error_ge1": total_ge1,
            "review_captured_error_ge1": review_ge1,
            "review_capture_rate_ge1": review_ge1 / total_ge1 if total_ge1 else math.nan,
            "total_error_ge2": total_ge2,
            "review_captured_error_ge2": review_ge2,
            "review_capture_rate_ge2": review_ge2 / total_ge2 if total_ge2 else math.nan,
            "risk_contract": (
                "auto-report candidates selected by non-truth algorithmic risk score; "
                "truth used only to audit this operating point"
            ),
        }
    )
    return row


def choose_recommendation(curve: pd.DataFrame, min_exact_rate: float, max_mae: float) -> pd.DataFrame:
    eligible = curve[
        (curve["auto_videos"] > 0)
        & (curve["abs_count_error_ge2"] == 0)
        & (curve["exact_rate"] >= min_exact_rate)
        & (curve["rr_mae"] <= max_mae)
    ].copy()
    if eligible.empty:
        eligible = curve[(curve["auto_videos"] > 0) & (curve["abs_count_error_ge2"] == 0)].copy()
    if eligible.empty:
        return pd.DataFrame()
    selected = eligible.sort_values(
        ["auto_coverage", "exact_rate", "rr_r2"],
        ascending=[False, False, False],
    ).head(1)
    selected = selected.copy()
    selected["recommendation"] = (
        "recommended_internal_auto_report_operating_point"
    )
    selected["recommendation_boundary"] = (
        "Use as an internal deployment-triage operating point only; freeze the "
        "threshold before any external evaluation and report coverage beside accuracy."
    )
    selected["selection_rule"] = (
        f"max coverage subject to exact_rate>={min_exact_rate:.2f}, "
        f"rr_mae<={max_mae:.2f}, and abs_count_error_ge2=0"
    )
    return selected


def markdown_table(df: pd.DataFrame, columns: list[str]) -> str:
    if df.empty:
        return "_No rows available._"
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for _, row in df.iterrows():
        values = []
        for column in columns:
            value = row.get(column, "")
            if isinstance(value, float):
                values.append("" if not np.isfinite(value) else f"{value:.4f}")
            else:
                values.append(str(value))
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines)


def write_report(output_path: Path, curve: pd.DataFrame, recommendation: pd.DataFrame) -> None:
    display_columns = [
        "operating_point",
        "auto_videos",
        "auto_coverage",
        "manual_review_load",
        "rr_r2",
        "rr_mae",
        "exact_count",
        "exact_rate",
        "exact_rate_wilson_low_95",
        "abs_count_error_ge1",
        "abs_count_error_ge2",
        "review_capture_rate_ge1",
    ]
    text = [
        "# RR Deployment Decision Curve",
        "",
        "This report evaluates automatic-report operating points for the current "
        "conservative signal-aware safe-gate RR prediction. The decision rule uses "
        "only the non-truth algorithmic review-risk score; reference RR and manual "
        "count are used only after selection to audit each operating point.",
        "",
        "## Recommended Internal Operating Point",
        "",
        markdown_table(
            recommendation,
            [
                "operating_point",
                "auto_videos",
                "auto_coverage",
                "manual_review_load",
                "rr_r2",
                "rr_mae",
                "exact_count",
                "exact_rate",
                "abs_count_error_ge2",
                "selection_rule",
            ],
        ),
        "",
        "## Coverage-Risk Curve",
        "",
        markdown_table(curve, display_columns),
        "",
        "## Manuscript Boundary",
        "",
        "Use this as an internal uncertainty-aware deployment analysis. Do not "
        "describe the threshold as prospectively validated, externally validated, "
        "or as a manual visual-quality score.",
    ]
    output_path.write_text("\n".join(text) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    input_root = args.input_root.resolve()
    predictions_path = input_root / f"{args.quality_prefix}_predictions.csv"
    if not predictions_path.exists():
        raise FileNotFoundError(f"Missing algorithmic quality predictions: {predictions_path}")
    data = pd.read_csv(predictions_path)
    thresholds = [0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70, 1.00]
    curve = pd.DataFrame([decision_row(data, threshold) for threshold in thresholds])
    recommendation = choose_recommendation(curve, args.min_exact_rate, args.max_mae)

    curve_path = input_root / f"{args.output_prefix}_deployment_decision_curve.csv"
    recommendation_path = input_root / f"{args.output_prefix}_deployment_decision_recommendation.csv"
    report_path = input_root / f"{args.output_prefix}_deployment_decision_report.md"
    curve.to_csv(curve_path, index=False)
    recommendation.to_csv(recommendation_path, index=False)
    write_report(report_path, curve, recommendation)

    print(f"Saved deployment decision curve: {curve_path}")
    print(f"Saved deployment decision recommendation: {recommendation_path}")
    print(f"Saved deployment decision report: {report_path}")
    if not recommendation.empty:
        print(recommendation[["operating_point", "auto_videos", "auto_coverage", "rr_r2", "rr_mae", "exact_count", "exact_rate"]].to_string(index=False))


if __name__ == "__main__":
    main()
